variable "cloudflare_zone"  {
  description = "DNS Zone"
  type        = string
}

variable "cloudflare_zone_id"  {
  description = "ID of your Cloudflare zone"
  type        = string
}

variable "cloudflare_account_id"  {
  description = "ID of your Cloudflare account"
  type        = string
}

variable "aws_region"  {
  description = "The region you want to deploy in"
  type        = string

  validation {
    condition = contains(["eu-west-1", "us-west-2", "us-east-1"], var.aws_region)
    error_message = "You can only deploy in supported regions: \"eu-west-1\", \"us-west-2\", \"us-east-1\""
  }
}

variable "aws_access_key" {
  description = "The access key for AWS"
  type        = string
}

variable "aws_secret_key" {
  description = "The secret for AWS"
  type        = string
}

variable "cloudflare_api_token" {
  description = "The API token used for Cloudflare"
  type        = string
}

variable "homeassistant_local_url"  {
  description = "The URL used to access Homeassistant in your local network"
  type        = string
}

variable "allowed_countries"  {
  description = "Access restriction to specific countries"
  type        = set(string)
  default     = []
}

variable "allowed_mails"  {
  description = "Access restriction to specific mail addresses"
  type        = set(string)
  default     = []
}

variable "function_name"  {
  description = "The name of your lambda function"
  type        = string
}

variable "alexa_skill_token"  {
  description = "That token generated by the alexa skill"
  type        = string
}

variable "ha_access_token"  {
  description = "The long lived access token generated in homeassistant"
  type        = string
}

variable "wrapper_secret"  {
  description = "The secret for the wrapper function. Can be randomly generated"
  type        = string
}
